### ISSUE TITLE
Failed to launch Cerbos: Error: Command failed

### ISSUE THREAD

**Issue by josephharkins** [cerbos/cerbos-compile-action#79]
Hi there!

I am getting error with this action, the cerbos setup action runs fine, it finds the policies fine, but this error comes up in the compile cerbos action:

`Error: Failed to launch Cerbos: Error: Command failed: /opt/hostedtoolcache/cerbosctl/0.29.0/x64/cerbos compile /home/runner/work/cerbos/cerbos/resource_policies --tests /home/runner/work/cerbos/cerbos/tests`

Here is the full log:

```
Run cerbos/cerbos-setup-action@v1
  with:
    github_token: ***
    version: latest
Version from input: latest
Operating System: Linux
Architecture: x86_64
Looking for asset cerbos_0.29.0_Linux_x86_64.tar.gz in Cerbos releases.
Downloading release from https://github.com/cerbos/cerbos/releases/download/v0.29.0/cerbos_0.29.0_Linux_x86_64.tar.gz.
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/95c1cdfe-931e-45c6-bfe5-488a1fb6ecb2 -f /home/runner/work/_temp/82318d0b-a537-4b55-ad36-f8b4f57dd873
Successfully extracted binaries to /home/runner/work/_temp/95c1cdfe-931e-45c6-bfe5-488a1fb6ecb2
Adding cerbos binaries to the cache
Cached the binary cerbos in /opt/hostedtoolcache/cerbos/0.29.0/x64
Cached the binary cerbosctl in /opt/hostedtoolcache/cerbosctl/0.29.0/x64
Adding cerbos binaries to path
Added the binary to path (/opt/hostedtoolcache/cerbos/0.29.0/x64)
Added the binary to path (/opt/hostedtoolcache/cerbosctl/0.29.0/x64)

Run cerbos/cerbos-compile-action@v1
  with:
    policyDir: resource_policies
    testDir: tests
Getting path to the cerbos binary
Succesfully got path to the cerbos binary: /opt/hostedtoolcache/cerbosctl/0.29.0/x64/cerbos
Running cerbos compile process.
Configured policy directory: /home/runner/work/cerbos/cerbos/resource_policies
Configured test directory: /home/runner/work/cerbos/cerbos/tests
Added --tests flag to the command as tests are enabled
Command to run: /opt/hostedtoolcache/cerbosctl/0.29.0/x64/cerbos compile /home/runner/work/cerbos/cerbos/resource_policies --tests /home/runner/work/cerbos/cerbos/tests
cerbos compile results
  cerbos: error: compile.Cmd.Run(): tests failed
  Error: Failed to launch Cerbos: Error: Command failed: /opt/hostedtoolcache/cerbosctl/0.29.0/x64/cerbos compile /home/runner/work/cerbos/cerbos/resource_policies --tests /home/runner/work/cerbos/cerbos/tests
  cerbos: error: compile.Cmd.Run(): tests failed
```

**Comment by charithe** [comment]
It looks like the action is trying to find tests in the `tests` directory at the root of your repository but I assume they are actually in the `resource_policies` directory? Could you please post the directory layout of your repo?

Either way, the error message is not great. We'll look into fixing that. Thanks for reporting.

**Comment by josephharkins** [comment]
Thanks for the reply, @charithe , they are in the tests directory as normally structured.

Pic of directory structure:
![image](https://github.com/cerbos/cerbos-compile-action/assets/47038639/4238d9ff-18fe-4259-b990-13667e436471)

Could it be something else then?

**Comment by oguzhand95** [comment]
```yaml
with:
  policyDir: resource_policies
  testDir: tests
```

Setting the `policyDir` to `resource_policies` makes Cerbos only search for the policies in that directory. If you import derived roles into your resource policies from the `derived_roles`directory, Cerbos will not be able to find those -- which is what seems to have happened here. Unfortunately, due to a bug in the compile action, the output from Cerbos was suppressed. We are working on a fix for that. 
Cerbos automatically discovers tests within the policy directory so you just need to set `policyDir` to the root of the repository to fix the compilation error.

**Comment by josephharkins** [comment]
Nice one thanks for the reply @oguzhand95 , should I set policyDir to ./ then?

**Comment by oguzhand95** [comment]
Yes, you can set it like this;
```yaml
with:
  policyDir: .
```

**Comment by josephharkins** [comment]
Have it working now, thanks!
